site_name: RenderCV App Docs
site_url: https://appdocs.rendercv.com/
site_description: Documentation of the RenderCV App
copyright: Copyright &copy; 2024 RenderCV

theme:
  name: material
  language: en
  logo: assets/images/logo.svg
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.copy # the copy-to-clipboard buttons for code blocks
    - content.action.view # view source button for pages
    - content.action.edit # view source button for pages
    - navigation.footer # the previous and next buttons in the footer
    - navigation.indexes # allow mother pages to have their own index pages
    - navigation.instant # instant navigation for faster page loads
    - navigation.instant.prefetch # prefetch pages for instant navigation
    - navigation.instant.progress # show progress bar for instant navigation
    - navigation.top # back to top button
    - search.highlight # highlight search results after going to a page
    - search.suggest # show search suggestions while typing
    - search.share # share search results with others
    - toc.follow # if toc sidebar doesn't fit, scroll to the active heading
    - content.code.annotate # allow annotations in code blocks
    - content.tabs.link # switch all the content tabs to the same label

markdown_extensions:
  # see https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/ for more pymdownx info
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # content tabs
      alternate_style: true
  - toc:
      permalink: true
      title: Page contents
  - admonition # blocks like note, warning, tip, etc.

plugins:
  - search
  - macros: # mkdocs-macros-plugin
      module_name: docs/update_entry_figures

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sinaatalay/rendercv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/rendercv/
