[project]
name = "rendercv-appdocs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mkdocs-material==9.5.45", "mkdocs-macros-plugin==1.3.7", "rendercv==1.14"]